/**
 * rest-schedule API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * <p>
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * <p>
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.arianit.ui.schedule.api;

import jakarta.ws.rs.core.Response;
import lombok.Getter;

import java.io.Serial;

@Getter
public class ApiException extends Exception {

    @Serial
    private static final long serialVersionUID = 1L;
    private Response response;

    public ApiException() {
        super();
    }

    public ApiException(Response response) {
        super("Api response has status code " + response.getStatus());
        this.response = response;
    }

}
