quarkus.http.port=\${PORT:8080}
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=schedule
quarkus.datasource.password=schedule
quarkus.datasource.jdbc.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/schedule}
quarkus.hibernate-orm.schema-management.strategy=update
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
# OIDC client configuration
quarkus.oidc.auth-server-url=http://localhost:8081/realms/schedule
quarkus.oidc.client-id=backend
quarkus.oidc.credentials.secret=secret
# Keycloak Admin Client configuration
quarkus.keycloak.admin-client.server-url=http://localhost:8081
quarkus.keycloak.admin-client.realm=schedule
quarkus.keycloak.admin-client.client-id=backend
quarkus.keycloak.admin-client.client-secret=secret
quarkus.keycloak.admin-client.grant-type=CLIENT_CREDENTIALS