/**
 * rest-schedule API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * <p>
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * <p>
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.arianit.ui.schedule.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;
import java.time.LocalTime;


@Getter
@Setter
public class Appointment {

    @JsonProperty("id")
    private Long id;

    @JsonProperty("title")
    private String title;

    @JsonProperty("description")
    private String description;

    @JsonProperty("location")
    private String location;

    @JsonProperty("date")
    private LocalDate date;

    @JsonProperty("startTime")
    private LocalTime startTime;

    @JsonProperty("endTime")
    private LocalTime endTime;

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public Appointment id(Long id) {
        this.id = id;
        return this;
    }

    public Appointment title(String title) {
        this.title = title;
        return this;
    }

    public Appointment description(String description) {
        this.description = description;
        return this;
    }

    public Appointment location(String location) {
        this.location = location;
        return this;
    }

    public Appointment date(LocalDate date) {
        this.date = date;
        return this;
    }

    public Appointment startTime(LocalTime startTime) {
        this.startTime = startTime;
        return this;
    }

    public Appointment endTime(LocalTime endTime) {
        this.endTime = endTime;
        return this;
    }

    /**
     * Create a string representation of this pojo.
     **/
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Appointment {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    location: ").append(toIndentedString(location)).append("\n");
        sb.append("    date: ").append(toIndentedString(date)).append("\n");
        sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
        sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

