/**
 * rest-schedule API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * <p>
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * <p>
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.arianit.ui.schedule.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import java.time.LocalTime;

public class Appointment {

    @JsonProperty("id")
    private Long id;

    @JsonProperty("title")
    private String title;

    @JsonProperty("description")
    private String description;

    @JsonProperty("location")
    private String location;

    @JsonProperty("date")
    private LocalDate date;

    @JsonProperty("startTime")
    private LocalTime startTime;

    @JsonProperty("endTime")
    private LocalTime endTime;

    @JsonProperty("user")
    private User user;

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Get id
     *
     * @return id
     **/
    public Long getId() {
        return id;
    }

    /**
     * Set id
     **/
    public void setId(Long id) {
        this.id = id;
    }

    public Appointment id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get title
     *
     * @return title
     **/
    public String getTitle() {
        return title;
    }

    /**
     * Set title
     **/
    public void setTitle(String title) {
        this.title = title;
    }

    public Appointment title(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Set description
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    public Appointment description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get location
     *
     * @return location
     **/
    public String getLocation() {
        return location;
    }

    /**
     * Set location
     **/
    public void setLocation(String location) {
        this.location = location;
    }

    public Appointment location(String location) {
        this.location = location;
        return this;
    }

    /**
     * Get date
     *
     * @return date
     **/
    public LocalDate getDate() {
        return date;
    }

    /**
     * Set date
     **/
    public void setDate(LocalDate date) {
        this.date = date;
    }

    public Appointment date(LocalDate date) {
        this.date = date;
        return this;
    }

    /**
     * Get startTime
     *
     * @return startTime
     **/
    public LocalTime getStartTime() {
        return startTime;
    }

    /**
     * Set startTime
     **/
    public void setStartTime(LocalTime startTime) {
        this.startTime = startTime;
    }

    public Appointment startTime(LocalTime startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Get endTime
     *
     * @return endTime
     **/
    public LocalTime getEndTime() {
        return endTime;
    }

    /**
     * Set endTime
     **/
    public void setEndTime(LocalTime endTime) {
        this.endTime = endTime;
    }

    public Appointment endTime(LocalTime endTime) {
        this.endTime = endTime;
        return this;
    }

    /**
     * Get user
     *
     * @return user
     **/
    public User getUser() {
        return user;
    }

    /**
     * Set user
     **/
    public void setUser(User user) {
        this.user = user;
    }

    public Appointment user(User user) {
        this.user = user;
        return this;
    }

    /**
     * Create a string representation of this pojo.
     **/
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Appointment {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    location: ").append(toIndentedString(location)).append("\n");
        sb.append("    date: ").append(toIndentedString(date)).append("\n");
        sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
        sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
        sb.append("    user: ").append(toIndentedString(user)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

