/**
 * rest-schedule API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * <p>
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * <p>
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.arianit.ui.schedule.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;

public class User {

    @JsonProperty("id")
    private Long id;

    @JsonProperty("name")
    private String name;

    @JsonProperty("surname")
    private String surname;

    @JsonProperty("username")
    private String username;

    @JsonProperty("email")
    private String email;

    @JsonProperty("password")
    private String password;

    @JsonProperty("birthday")
    private LocalDate birthday;

    @JsonProperty("active")
    private Boolean active;

    @JsonProperty("image")
    private String image;

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private static String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Get id
     *
     * @return id
     **/
    public Long getId() {
        return id;
    }

    /**
     * Set id
     **/
    public void setId(Long id) {
        this.id = id;
    }

    public User id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    public String getName() {
        return name;
    }

    /**
     * Set name
     **/
    public void setName(String name) {
        this.name = name;
    }

    public User name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get surname
     *
     * @return surname
     **/
    public String getSurname() {
        return surname;
    }

    /**
     * Set surname
     **/
    public void setSurname(String surname) {
        this.surname = surname;
    }

    public User surname(String surname) {
        this.surname = surname;
        return this;
    }

    /**
     * Get username
     *
     * @return username
     **/
    public String getUsername() {
        return username;
    }

    /**
     * Set username
     **/
    public void setUsername(String username) {
        this.username = username;
    }

    public User username(String username) {
        this.username = username;
        return this;
    }

    /**
     * Get email
     *
     * @return email
     **/
    public String getEmail() {
        return email;
    }

    /**
     * Set email
     **/
    public void setEmail(String email) {
        this.email = email;
    }

    public User email(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get password
     *
     * @return password
     **/
    public String getPassword() {
        return password;
    }

    /**
     * Set password
     **/
    public void setPassword(String password) {
        this.password = password;
    }

    public User password(String password) {
        this.password = password;
        return this;
    }

    /**
     * Get birthday
     *
     * @return birthday
     **/
    public LocalDate getBirthday() {
        return birthday;
    }

    /**
     * Set birthday
     **/
    public void setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }

    public User birthday(LocalDate birthday) {
        this.birthday = birthday;
        return this;
    }

    /**
     * Get active
     *
     * @return active
     **/
    public Boolean getActive() {
        return active;
    }

    /**
     * Set active
     **/
    public void setActive(Boolean active) {
        this.active = active;
    }

    public User active(Boolean active) {
        this.active = active;
        return this;
    }

    /**
     * Get image
     *
     * @return image
     **/
    public String getImage() {
        return image;
    }

    /**
     * Set active
     **/
    public void setImage(String image) {
        this.image = image;
    }

    public User image(String image) {
        this.image = image;
        return this;
    }

    public String getInitials() {
        return "" + name.charAt(0) + surname.charAt(0);
    }

    /**
     * Create a string representation of this pojo.
     **/
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class User {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
        sb.append("    username: ").append(toIndentedString(username)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("    password: ").append(toIndentedString(password)).append("\n");
        sb.append("    birthday: ").append(toIndentedString(birthday)).append("\n");
        sb.append("    active: ").append(toIndentedString(active)).append("\n");
        sb.append("    image: ").append(toIndentedString(image)).append("\n");
        sb.append("}");
        return sb.toString();
    }
}

